[build]
  base = ""
  publish = "client/.next"
  command = "npm run build-netlify"

# Redirect API requests to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Handle client-side routing for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Install dependencies for Netlify Functions
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
